### ISSUE TITLE
Definition of live/dead organoid

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [adiezsanchez/intestinal_organoid_yolov8#1]
Hello team, thanks for this repo. I was wondering how the organoids are classified as live/dead. Based on intensity or shape or something else?

Thanks!
Ajinkya

**Comment by adiezsanchez** [comment]
Hello Ajinkya, dying/overgrown organoids appear very dark under brightfield microscopy. This is because all the cells that would normally be shed into the intestinal lumen are being shed inside the organoid. So the YOLOv8 model we trained is picking those features. Morphology wise they are not so different from differentiated organoids until late stages where dead organoids lose their structural integrity and "disintegrate".

**Comment by ajinkya-kulkarni** [comment]
Ah ok - thanks for clarifying!
And to be a bit more specific - below which values of intensity do you consider the organoid dead? Say if you scale the image be lie between 0-255, what would be the threshold value? And how would/have you validated that particular value?

Thanks and regards,
Ajinkya

**Comment by adiezsanchez** [comment]
Hi again, there is not a defined value below which the researchers that annotated the ground truth images considered the organoids dead, but rather general appearance (morphology and darkness). Whenever I find some time I can implement an intensity measurement using skimage.measure and plot the grey values to get an idea of these for the 3 different classes. So far it has limited functionality since the main interest of the users is getting basic morphology and counts of spheroids and differentiated organoids.
